# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://yuzp1996.github.io/
date_format: "ordinal"
title: TopGun

subtitle: "Change the world with my code"
description: "鱼狗狗的个人博客"
keywords: 于志鹏
favicon: /favicon.ico
timezone: Asia/Tangshan
encoding: "utf-8"
source_code: https://github.com/izhangzhihao/izhangzhihao.github.io
side_bar_repo_limit: 5
# ---------------- #
#      Author      #
# ---------------- #
author: 于志鹏
organization: 华北理工大学智慧应用软件研发工作室
# organization_url: 

location: TangShan, China
email: yuzp1996@qq.com
# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页
  -
    href: /MySkillTree/
    label: 我的技能树

  -
    href: /about/
    label: 关于我

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
#github_username: izhangzhihao
#facebook_username: izhangzhihao
#weibo_username: izhangzhihao

#zhihu_username: 于志鹏
#twitter_username: izhangzhihao

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: yuzp1996
disqus_username: yuzp1996
# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-96242466-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_language_keywords: [Python, Html, jquery]
skill_web_app_keywords: [Django, nginx,Flask]
